/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tareascortas;

import java.awt.Color;

/**
 *
 * @author Esteban
 */
public class PruebaBotin extends javax.swing.JFrame {
    boolean Estado1;
    boolean Estado2;
    boolean Estado3;
    //PriorityQueue<String> Cola; 
    /**
     * Creates new form PruebaBotin
     */
    public PruebaBotin() {
        Estado1=false;
        Estado2=false;
        Estado3=false;
        initComponents();
        //Cola=new PriorityQueue<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Cajero1 = new javax.swing.JButton();
        Cajero2 = new javax.swing.JButton();
        Cajero3 = new javax.swing.JButton();
        Letrero = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Cajero1.setText("Cajero1");
        Cajero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cajero1ActionPerformed(evt);
            }
        });

        Cajero2.setText("Cajero2");
        Cajero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cajero2ActionPerformed(evt);
            }
        });

        Cajero3.setText("Cajero3");
        Cajero3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cajero3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Cajero3)
                            .addComponent(Cajero2)
                            .addComponent(Cajero1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(Letrero)))
                .addContainerGap(280, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(Cajero1)
                .addGap(18, 18, 18)
                .addComponent(Cajero2)
                .addGap(18, 18, 18)
                .addComponent(Cajero3)
                .addGap(18, 18, 18)
                .addComponent(Letrero)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Cajero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cajero1ActionPerformed
        if(Estado1==false){
            Letrero.setText("Pasar a la Caja1");
            Cajero1.setText("Cajero esta Ocupado");
            Cajero1.setBackground(Color.red);
            Estado1=true;
        }
        else{
            Cajero1.setText("Cajero esta Libre");
            Cajero1.setBackground(Color.green);
            Estado1=false;
        }
    }//GEN-LAST:event_Cajero1ActionPerformed

    private void Cajero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cajero2ActionPerformed
        if(Estado2==false){
            Letrero.setText("Pasar a la Caja2");
            Cajero2.setText("Cajero esta Ocupado");
            Cajero2.setBackground(Color.red);
            Estado2=true;
        }
        else{
            Cajero2.setText("Cajero esta Libre");
            Cajero2.setBackground(Color.green);
            Estado2=false;
        }
    }//GEN-LAST:event_Cajero2ActionPerformed

    private void Cajero3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cajero3ActionPerformed
        if(Estado3==false){
            Letrero.setText("Pasar a la Caja3");
            Cajero3.setText("Cajero esta Ocupado");
            Cajero3.setBackground(Color.red);
            Estado3=true;
        }
        else{
            Cajero3.setText("Cajero esta Libre");
            Cajero3.setBackground(Color.green);
            Estado3=false;
        }
    }//GEN-LAST:event_Cajero3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PruebaBotin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PruebaBotin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PruebaBotin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PruebaBotin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PruebaBotin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cajero1;
    private javax.swing.JButton Cajero2;
    private javax.swing.JButton Cajero3;
    private javax.swing.JLabel Letrero;
    // End of variables declaration//GEN-END:variables
}
